Few sample programs added.
TomerADev/mano-simulator pull request #6
Opened 2021-07-09 20:04 UTC by abdurrahmanekr

Hello @TomerAberbach , I found this project to study for the computer architecture lesson and it helped me a lot, thank you. However, at first I did not know how to use label while running mano simulator. So I had to read the source codes. It turns out that a label can be created with `,` :). I've included a few simple examples, thinking it might be helpful to someone else.

Thank you again.

2021-07-09 22:04 UTC, TomerAberbach requested changes
Thanks for the contribution! Glad you found the simulator useful. Just have some minor comments

2021-07-09 22:04 UTC, TomerAberbach commented on examples.md
> +### Change RESULT variable to !X
Should use `##` instead of `###` for the second level of headings here and below

2021-07-09 22:04 UTC, TomerAberbach commented on examples.md
> +Here are some simple examples you can do with Mano simulator. You can learn how to write a mano program by taking examples from these codes.
I would just remove this introductory text after the heading. I don't think it really adds anything

2021-07-09 22:04 UTC, TomerAberbach commented on examples.md
> +ORG 0
I think the default starting memory location is address 0 so `ORG 0` should be unnecessary in this case, but I haven't run the simulator in a while so feel free to correct me if that's not right. If that is right, then just remove `ORG 0` in the other examples as well

2021-07-09 22:04 UTC, TomerAberbach commented on examples.md
> +HLT
For this code examples and the others add a blank line between the code and the data

2021-07-09 22:04 UTC, TomerAberbach commented on readme.md
> +[Example mano programs](./examples.md)
```suggestion
See [example programs](examples.md).
```

2021-07-09 22:04 UTC, TomerAberbach commented on examples.md
> +### Change RESULT variable to !X
Include backticks around all variables in text outside of code blocks (e.g. `RESULT` and `X` instead of RESULT and X)

2021-07-09 22:04 UTC, TomerAberbach commented on examples.md
> +```
Add what the output/result is of each program after the code block. I see you already added the result for some of the examples so just move those below the code.

2021-07-10 06:24 UTC, abdurrahmanekr commented on examples.md
> +ORG 0
Yes it was unnecessary so I deleted it.

2021-07-10 21:06 UTC, TomerAberbach requested changes

2021-07-10 21:06 UTC, TomerAberbach commented on examples.md
> +HLT
Sorry, I think I wasn't clear enough. I would consider `HLT` to be part of the program/code so could you put the blank line between `HLT` (the final instruction) and the labeled data?

2021-07-12 22:48 UTC, TomerAberbach commented
Looks great! Once again, thanks for the contribution!

2021-07-12 22:48 UTC, merged